name = "FractionalNeuralSampling"
uuid = "1a146edb-494d-4c3d-929d-e214933c7497"
authors = ["brendanjohnharris <bhar9988@uni.sydney.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"
